res_dir: ./train/results
ex_name: UBC2Model
dataset: CATH4.2
model_name: UBC2Model
# lr: 0.0002
# lr_scheduler: onecycle
# lr_scheduler: cosine
offline: 1
seed: 112
pretrained_path: ''
batch_size: 2
accumulate_grad_batches: 1
num_workers: 0
min_length: 40
data_root: ./data/
# epoch: 50
augment_eps: 0.0
geo_layer: 3
attn_layer: 3
node_layer: 3
edge_layer: 3
encoder_layer: 12
hidden_dim: 128
dropout: 0.0
k_neighbors: 30
virtual_atom_num: 24
bc_encoder_layer: 2

mask_rate: 0.1
bc_mask_how: token
modal_mask_ratio: 0.

contrastive_pretrain_both: false
contrastive_loss_global_alpha: 0.01
contrastive_loss_local_alpha: 1.

if_struc_only: false
# checkpoint_path: "./UBC2Model.ckpt"
